apiVersion: v2
name: ollama
description: Get up and running with large language models locally.

type: application

version: 0.67.0

appVersion: "0.4.3"

annotations:
  artifacthub.io/category: ai-machine-learning
  artifacthub.io/changes: |
    - kind: added
      description: add load model in memory at startup 
    - kind: changed
      description: Change ollama.models list to ollama.models.pull list

kubeVersion: "^1.16.0-0"
home: https://ollama.ai/
icon: https://ollama.ai/public/ollama.png
keywords:
  - ai
  - llm
  - llama
  - mistral
sources:
  - https://github.com/ollama/ollama
  - https://github.com/otwld/ollama-helm
maintainers:
  - name: OTWLD
    email: contact@otwld.com
