apiVersion: v2
name: ollama
description: Get up and running with large language models locally.

type: application

version: 0.17.0

appVersion: "0.1.27"

annotations:
  artifacthub.io/category: ai-machine-learning
  artifacthub.io/changes: |
    - kind: changed
      description: upgrade ollama to 0.1.27


kubeVersion: "^1.16.0-0"
home: https://ollama.ai/
icon: https://ollama.ai/public/ollama.png
keywords:
  - ai
  - llm
  - llama
  - mistral
sources:
  - https://github.com/ollama/ollama
  - https://github.com/otwld/ollama-helm
maintainers:
  - name: Outworld
    email: tech@outworld.fr
